name: OWASP ZAP Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Setiap hari Minggu

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Buggy Notes App
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "https://buggy-notes1.netlify.app/"
          # Gunakan tanda hubung atau garis bawah
          artifact_name: "zap-scan-report"
